### ISSUE TITLE
FurElise example does not compile with `stack build`

### ISSUE THREAD

**Issue by OlivierNicole** [DimaSamoz/mezzo#1]
On master, when simply doing `stack build` in the `examples` directory, I get the following error:

```
Preprocessing library mezzo-examples-0.1.0.0...
[ 5 of 13] Compiling FurElise.Theme   ( src/FurElise/Theme.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/FurElise/Theme.o )

/home/olivier/prog/haskell/mezzo/examples/src/FurElise/Theme.hs:16:21: error:
    • Compound intervals are not permitted in melody: A and E__
    • In the first argument of ‘(:|)’, namely
        ‘melody :~> r :<< a__ :| e_ :| a_ :| c :| e :| a :<< e__’
      In the first argument of ‘(:|)’, namely
        ‘melody :~> r :<< a__ :| e_ :| a_ :| c :| e :| a :<< e__ :| e_’
      In the first argument of ‘(:~<.)’, namely
        ‘melody :~> r :<< a__ :| e_ :| a_ :| c :| e :| a :<< e__ :| e_
         :| gs_’
```

**Comment by DimaSamoz** [comment]
Ah, thank you for this. It's easy enough to explain, I only added the compound melodic interval rules a few days ago and forgot to see whether the examples still worked. The easiest solution is probably just turning off rule-checking for that section :) It is somewhat cheating but the rule-checking is more useful when composing new music and not transcribing existing pieces into the EDSL.
